version: '3'
services:
  api:
    image: node:12
    command: npm run dev
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 3002:3000
    depends_on:
      - mongo

  mongo:
    image: mongo:4
    ports:
      - 27017:27017
